import { I18nModule } from '../../core/i18n/i18n.module';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { JobSummary } from 'src/app/core/models/api.models';
@Component({
 selector: 'app-job-card', standalone: true, imports: [I18nModule, CommonModule, RouterModule],
 template: `<article class="job-card"><div class="job-company"><img [src]="job.companyDTO?.avatarURL || '/assets/images/avatar.svg'" (error)="imageError($event)" alt="" width="56" height="56"><div><p>{{ job.companyName || job.companyDTO?.companyName || ('Công ty tuyển dụng' | t) }}</p><h3><a [routerLink]="['/candidate/jd-detail', job.jobId]">{{ job.title }}</a></h3></div></div><p class="salary">{{ job.salary || ('Lương thỏa thuận' | t) }}</p><p class="location"><i class="bi bi-geo-alt" aria-hidden="true"></i> {{ job.address || ('Địa điểm trao đổi khi phỏng vấn' | t) }}</p><div class="job-tags"><span *ngIf="job.categoryName">{{ job.categoryName }}</span><span *ngIf="job.employmentTypeName">{{ job.employmentTypeName }}</span><span *ngIf="job.levelTitle">{{ job.levelTitle }}</span></div><div class="job-footer"><a class="job-action" [routerLink]="['/candidate/jd-detail', job.jobId]">{{ 'Xem công việc' | t }} <i class="bi bi-arrow-up-right" aria-hidden="true"></i></a><small [class.expired]="job.isExpired">{{ job.isExpired ? ('Đã hết hạn' | t) : ('Hạn ứng tuyển: ' | t) + (job.expiredDate || ('Chưa cập nhật' | t)) }}</small><button *ngIf="canSave" type="button" (click)="saveToggle.emit(job.jobId)" [disabled]="saving" [attr.aria-label]="(saved ? ('Bỏ lưu ' | t) : ('Lưu ' | t)) + job.title" [attr.aria-pressed]="saved"><i [class]="saved ? 'bi bi-bookmark-fill' : 'bi bi-bookmark'" aria-hidden="true"></i> {{ (saving ? 'Đang lưu…' : saved ? 'Đã lưu' : 'Lưu') | t }}</button></div></article>`,
 styles: [`.job-card{height:100%;padding:1.25rem;border:1px solid var(--border-color);border-radius:1rem;background:var(--surface-color);color:var(--text-color);display:flex;flex-direction:column;gap:.85rem}.job-company{display:flex;align-items:flex-start;gap:.85rem}.job-company img{object-fit:contain;border-radius:.7rem;border:1px solid var(--border-color);flex-shrink:0}.job-company div{min-width:0}.job-company p{font-size:.85rem;color:var(--muted-text-color);margin:0 0 .4rem}.job-company h3{font-size:1.1rem;margin:0;line-height:1.5}.job-company a{color:var(--text-color);text-decoration:none}.job-company a:hover{color:var(--accent-color)}.salary{font-weight:650;color:var(--accent-color)}.job-card>p{margin:0}.location{font-size:.9rem;color:var(--muted-text-color)}.job-tags{display:flex;flex-wrap:wrap;gap:.4rem}.job-tags span{font-size:.75rem;padding:.25rem .5rem;background:var(--surface-muted-color);border-radius:.4rem}.job-footer{display:flex;flex-wrap:wrap;align-items:center;gap:.75rem;justify-content:space-between;margin-top:auto;padding-top:.5rem}.job-footer small{color:var(--muted-text-color)}.job-footer button{border:1px solid var(--border-color);border-radius:.6rem;padding:.45rem .6rem;background:var(--surface-color);color:var(--accent-color)}.job-card{position:relative;overflow:hidden;box-shadow:0 5px 16px #18345c0a;transition:transform .18s,box-shadow .18s,border-color .18s}.job-card:before{content:"";position:absolute;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,#1789ea,#7750df);opacity:.6}.job-card:hover{transform:translateY(-3px);box-shadow:0 12px 28px #18345c1c;border-color:var(--accent-color)}.job-company img{background:var(--surface-muted-color);padding:.3rem}.job-action{font-size:.85rem;font-weight:700;color:var(--accent-color);text-decoration:none}.job-footer small{flex-basis:100%;order:3}.job-footer button[aria-pressed=true]{background:var(--accent-soft);border-color:var(--accent-color)}@media(prefers-reduced-motion:reduce){.job-card{transition:none;transform:none}}button:disabled{opacity:.5}button:focus-visible,a:focus-visible{outline:3px solid var(--focus-ring);outline-offset:3px}`]
})
export class JobCardComponent {
 @Input({ required: true }) job!: JobSummary; @Input() canSave = false; @Input() saved = false; @Input() saving = false;
 @Output() saveToggle = new EventEmitter<number>();
 imageError(event: Event): void { const image = event.target as HTMLImageElement; if (!image.src.endsWith('/assets/images/avatar.svg')) image.src = '/assets/images/avatar.svg'; }
}
