export interface Line { vi: string; en: string }
export const line = (vi: string, en: string): Line => ({ vi, en });
export type VoiceId = 'clarity' | 'care' | 'grit' | 'chaos';
export interface Voice { id: VoiceId; icon: string; name: Line; aside: Line }
export const VOICES: Voice[] = [
 { id:'clarity', icon:'compass', name:line('La Bàn','The Compass'), aside:line('Đề nghị định nghĩa từ “ổn”.','Please define “fine”.') },
 { id:'care', icon:'heart-pulse', name:line('Tim Đèn','The Porch Light'), aside:line('Có người đang cố tỏ ra không cần ai.','Someone is pretending they need nobody.') },
 { id:'grit', icon:'wrench-adjustable', name:line('Cờ Lê','The Wrench'), aside:line('Ta sửa được. Có lẽ. Đưa băng keo đây.','We can fix it. Probably. Pass the tape.') },
 { id:'chaos', icon:'lightning-charge', name:line('Tia Lệch','The Bad Idea'), aside:line('Nếu đây là điềm báo, ta có thể mặc cả.','If this is an omen, we can negotiate.') }
];
export interface Choice { voice: VoiceId; text: Line; reply: Line; souvenir: Line }
export interface Scene { title: Line; place: Line; text: Line; art: 'street' | 'city'; choices: Choice[] }
const choice = (voice:VoiceId,vi:string,en:string,replyVi:string,replyEn:string,itemVi:string,itemEn:string):Choice =>
 ({voice,text:line(vi,en),reply:line(replyVi,replyEn),souvenir:line(itemVi,itemEn)});
export const SCENES: Scene[] = [
 { title:line('Thứ Hai bị trả lại','Monday, Returned to Sender'), place:line('Trạm xe / 06:61','Bus stop / 06:61'), art:'street',
 text:line('Bạn tỉnh dậy ở trạm xe với một phong bì ghi: “Ngày mai của quý khách bị thiếu giấy tờ.” Thành phố vẫn sáng đèn. Đồng hồ hiển thị 06:61, rất tự tin. Một chiếc xe buýt không số đỗ lại. Tài xế là một cái áo mưa, bên trong có thể có người. “Sở Ngày Mai,” nó nói. “Đi không?”','You wake at a bus stop holding an envelope: “Your tomorrow is missing paperwork.” The city is still lit. The clock says 06:61 with impressive conviction. An unnumbered bus arrives. Its driver is a raincoat, possibly occupied. “Department of Tomorrow,” it says. “Coming?”'),
 choices:[
 choice('clarity','Hỏi xe đi đâu, rồi mới lên.','Ask where it goes before boarding.','Áo mưa đưa bạn bản đồ. Mọi đường đều ghi “còn tùy”. Ít ra bản đồ thành thật.','The raincoat hands you a map. Every road says “it depends”. At least the map is honest.','Bản đồ còn tùy','A map of it depends'),
 choice('care','Hỏi áo mưa có lạnh không.','Ask whether the raincoat is cold.','“Không ai hỏi câu đó cả.” Nó tăng nhiệt độ xe một độ. Một cuộc cách mạng rất nhỏ.','“Nobody asks that.” It turns the heating up one degree. A very small revolution.','Một độ ấm','One degree of warmth'),
 choice('grit','Đẩy giúp xe. Nó có vẻ cần.','Give the bus a push. It looks like it needs one.','Xe đang nổ máy. Nhưng tài xế vẫn cảm ơn. Đôi khi người ta cần có ai đứng cùng phía.','The engine is already running. The driver thanks you anyway. Sometimes people just need someone on their side.','Vết dầu trên tay','An oily handprint'),
 choice('chaos','Hỏi có giảm giá cho người đến từ ngày hôm qua không.','Ask for the yesterday-person discount.','Nó bấm vé. “Hạng phổ thông siêu thực.” Bạn được miễn phí. Lý do tài chính không được tiết lộ.','It punches a ticket. “Surreal economy class.” Your fare is waived. The fiscal reasoning is classified.','Vé siêu thực','A surreal economy ticket') ] },
 { title:line('Lấy số chờ chính mình','Please Wait for Yourself'), place:line('Sảnh tiếp nhận / Tầng có lẽ','Intake hall / Floor perhaps'), art:'street',
 text:line('Máy lấy số nhả ra số 0. Trên bảng điện, số đang được gọi cũng là 0. Không ai nhúc nhích. Một viên chức đặt trước bạn tờ đơn: “Điểm yếu lớn nhất của bạn?” Ông ấy ngáp. Cái ngáp có đóng dấu. Phía sau quầy, chậu cây giả đang héo vì lý do hành chính.','The ticket machine gives you number zero. The display also calls zero. Nobody moves. A clerk slides over a form: “Your greatest weakness?” He yawns. The yawn is officially stamped. Behind him, a plastic plant is dying for administrative reasons.'),
 choices:[
 choice('clarity','“Câu hỏi này dùng để hiểu tôi hay để loại tôi?”','“Is this meant to understand me, or disqualify me?”','Ông ấy ngừng ngáp. “Câu hỏi phụ rất nguy hiểm. Tôi thích.” Ông gạch một ô mà trước đó không tồn tại.','He stops yawning. “Dangerous follow-up. I like it.” He ticks a box that did not previously exist.','Ô chưa từng tồn tại','A previously nonexistent checkbox'),
 choice('care','“Tôi hay quên mình cũng là một người cần nghỉ.”','“I forget I am also a person who needs rest.”','Ông viên chức đẩy một cốc nước sang. Không có diễn văn. Nước cũng không đòi bạn cải thiện bản thân.','He pushes a glass of water across. No speech. The water does not require you to become a better person.','Cốc nước không KPI','Water without targets'),
 choice('grit','“Tôi cứ tự làm hết. Đang tập nhờ giúp.”','“I keep doing everything myself. Practising asking for help.”','“Tốt. Nhờ tôi đóng dấu nhé?” Bạn nhờ. Ông đóng. Một kỹ năng mềm vừa phát ra tiếng CỘP.','“Good. Ask me to stamp this?” You ask. He stamps. A soft skill makes a satisfyingly hard THUNK.','Con dấu nhờ giúp','The asking-for-help stamp'),
 choice('chaos','“Tôi từng tin máy in biết sợ.”','“I once believed printers could feel fear.”','Từ phòng bên, máy in ré lên. Viên chức nhìn bạn, rồi nhìn tờ đơn. “Không ghi câu đó vào hồ sơ.”','A printer shrieks in the next room. He looks at you, then the form. “We are keeping that off the record.”','Bí mật của máy in','The printer’s secret') ] },
 { title:line('Cầu thang tới gần đúng','A Staircase to Nearly'), place:line('Khu bảo trì / 11:03','Maintenance / 11:03'), art:'street',
 text:line('Thang máy báo “đang phát triển bản thân” và từ chối phục vụ. Bạn đi cầu thang, gặp một kỹ thuật viên đang giữ hai đầu dây điện không nối vào đâu. “Nếu nối lại, đèn sẽ sáng,” cô nói. “Nhưng tôi chưa biết đèn của ai.” Bên cạnh là một nút đỏ ghi: ĐỪNG BIẾN VIỆC NÀY THÀNH BÀI HỌC.','The lift announces it is “working on itself” and declines service. On the stairs, a technician holds two wires connected to nothing. “Join these and a light comes on,” she says. “Not sure whose.” A red button reads: DO NOT TURN THIS INTO A LIFE LESSON.'),
 choices:[
 choice('clarity','Tìm nhãn dây trước. Không phải đèn nào cũng nên bật.','Check the wiring labels. Not every light should be switched on.','Nhãn ghi: “Phòng nghỉ.” Cô bật đèn. Một cái ghế, ở đâu đó, thôi cảm thấy bị bỏ quên.','The label reads “Break room”. She switches it on. Somewhere, a chair stops feeling forgotten.','Nhãn phòng nghỉ','A break-room label'),
 choice('care','Giữ đèn pin cho cô ấy.','Hold the torch for her.','Bạn không sửa dây. Bạn giúp người đang sửa dây nhìn rõ hơn. Cô khẽ gật. Cầu thang bớt tối.','You do not fix the wire. You help the person fixing it see. She nods. The stairs grow less dark.','Đốm sáng đứng cùng','A light held steady'),
 choice('grit','Ngắt nguồn, rồi cùng kiểm tra.','Isolate the power, then check it together.','“Cuối cùng cũng có người không lao vào làm anh hùng.” Cô đưa bạn găng tay. Anh hùng ít điện giật hơn.','“Finally, someone not rushing to be a hero.” She hands you gloves. Heroism becomes less electrocution-prone.','Găng tay của người tỉnh','Sensible gloves'),
 choice('chaos','Bấm nút. Bài học tự lo thân nó.','Press the button. The life lesson can fend for itself.','Một loa phát: “Bạn được phép có một ngày vô nghĩa.” Cả hai đứng im, hưởng đặc quyền hiếm có.','A speaker says: “You are allowed one meaningless day.” You both stand still, enjoying this rare privilege.','Giấy phép vô nghĩa','A permit for pointlessness') ] },
 { title:line('Quán cà phê của những bản nháp','The Café of Unsent Drafts'), place:line('Ban công / Giờ chưa quyết','Balcony / Time undecided'), art:'city',
 text:line('Ngoài ban công, cả thành phố nằm giữa những vách đá, như ai đó đã quên nới lỏng vai. Quán chỉ bán cà phê và những câu chưa nói. Người pha chế đưa bạn một chiếc cốc chứa giọng của bạn năm ngoái: “Đáng lẽ mình phải…” Cốc không đầy nổi. Phía xa, một cửa sổ sáng lên rồi tắt.','Beyond the balcony, the city sits between cliffs, as if someone forgot to unclench their shoulders. The café serves coffee and things left unsaid. The barista gives you a cup containing last year’s voice: “I should have…” It never fills. Far away, a window lights up, then goes dark.'),
 choices:[
 choice('clarity','Đổi “đáng lẽ” thành một việc nhỏ có ngày hẹn.','Trade “should have” for one small thing with a date.','Bạn viết: “Thứ Sáu, gửi bản nháp.” Cốc chịu đầy. Tương lai thích địa chỉ cụ thể.','You write: “Friday, send the draft.” The cup finally fills. The future appreciates a forwarding address.','Tờ hẹn thứ Sáu','A Friday appointment'),
 choice('care','Mời phiên bản năm ngoái ngồi xuống.','Invite last year’s self to sit down.','Người đó trông mệt hơn trong trí nhớ. Bạn không tha thứ mọi chuyện. Bạn chỉ thôi đuổi họ ra ngoài mưa.','They look more tired than you remember. You do not forgive everything. You just stop leaving them out in the rain.','Ghế cho người cũ','A chair for who you were'),
 choice('grit','Uống. Đắng thì uống thêm nước.','Drink it. If it is bitter, have water too.','Cà phê không chữa cuộc đời. Nó giúp bạn tỉnh vừa đủ để rửa cốc. Hôm nay, thế là một tiến bộ.','Coffee does not repair a life. It makes you awake enough to wash the cup. Today, that counts as progress.','Chiếc cốc đã rửa','A washed cup'),
 choice('chaos','Gọi hai phần “mình đã cố rồi”, thêm đá.','Order two “I did try”s, over ice.','Người pha chế bật cười. Giọng năm ngoái cũng cười. Lần đầu trong ngày, không ai cần thắng.','The barista laughs. Last year laughs too. For the first time today, nobody needs to win.','Hai phần đã cố','Two servings of trying') ] },
 { title:line('Hội đồng rất nghiêm túc','The Extremely Serious Committee'), place:line('Phòng 404 / Không tìm thấy kết luận','Room 404 / Conclusion not found'), art:'street',
 text:line('Hội đồng gồm ba chiếc ghế và một con bồ câu. Bồ câu chủ trì. “Chúng tôi đã xác định kiểu tính cách của bạn,” nó nói, đẩy tới một biểu đồ tròn hoàn toàn màu xám. “Bạn thuộc nhóm Người.” Dưới bàn, máy hủy giấy ăn các nhãn tính cách với vẻ thỏa mãn chuyên nghiệp.','The committee consists of three chairs and a pigeon. The pigeon presides. “We have determined your personality type,” it says, presenting an entirely grey pie chart. “You are a Person.” Under the desk, a shredder eats personality labels with professional satisfaction.'),
 choices:[
 choice('clarity','Hỏi mẫu nghiên cứu có bao gồm người ngoài hội đồng không.','Ask whether the study included anyone outside this room.','“Có. Một người.” Nó nhìn bạn. Biểu đồ tròn khẽ đỏ mặt, điều trước đó được cho là bất khả thi.','“Yes. One.” It looks at you. The pie chart blushes, a previously impossible finding.','Biểu đồ biết ngượng','An embarrassed pie chart'),
 choice('care','Cảm ơn rồi hỏi có ai muốn ăn trưa không.','Thank them and ask if anyone wants lunch.','Cả ba chiếc ghế dịch lại. Bồ câu gật. Bạn đã giải quyết vấn đề mà bản báo cáo không nhận ra.','All three chairs shuffle closer. The pigeon nods. You have solved a problem the report failed to identify.','Lời mời ăn trưa','An invitation to lunch'),
 choice('grit','Xin nhận xét về một việc mình làm, thay vì về cả con người.','Ask for feedback on something you did, rather than your entire being.','Bồ câu suy nghĩ. “Bạn tới đây dù xe buýt vô lý. Khá.” Một nhận xét nhỏ, vừa vặn túi áo.','The pigeon thinks. “You showed up despite the ridiculous bus. Decent.” A small observation, pocket-sized.','Nhận xét vừa túi','Pocket-sized feedback'),
 choice('chaos','Đề cử bồ câu làm nhóm tính cách thứ năm.','Nominate Pigeon as the fifth personality type.','Đề xuất được thông qua 4–0. Bạn vừa làm khoa học lùi một bước, và bữa trưa tiến hai bước.','Motion carried, four to zero. Science takes one step backward. Lunch takes two steps forward.','Chứng nhận hệ Bồ Câu','Certified Pigeon Type') ] },
 { title:line('Cửa ra không yêu cầu mật khẩu','The Exit Has No Password'), place:line('Mái nhà / Trước ngày mai','Rooftop / Before tomorrow'), art:'city',
 text:line('Trên mái nhà, một cánh cửa đứng một mình. Không có tường. Phong bì trong túi bạn nhẹ đi. Tờ giấy cuối cùng hỏi: “Mang gì sang ngày mai?” Bốn giọng nói trong đầu im lặng. Không phải vì đã hiểu hết. Vì lần này, câu trả lời được quyền thuộc về bạn.','On the roof, a door stands without a wall. The envelope in your pocket has grown lighter. Its last page asks: “What will you carry into tomorrow?” The four voices fall quiet. Not because everything is understood. Because this time, the answer is allowed to be yours.'),
 choices:[
 choice('clarity','Một hướng đi. Không cần cả bản đồ.','A direction. I do not need the whole map.','Bạn đặt la bàn vào túi. Kim vẫn rung. Đủ tốt để đi bước đầu.','You pocket the compass. Its needle still trembles. Good enough for a first step.','Một hướng, chưa phải định mệnh','A direction, not a destiny'),
 choice('care','Một chỗ trống cho người khác, và cho mình.','Room for another person. Room for me, too.','Cánh cửa rộng hơn một chút. Bạn không mang được cả thế giới. Bạn có thể chừa một ghế.','The door widens a little. You cannot carry the world. You can leave a chair open.','Chỗ trống có chủ ý','Deliberate breathing room'),
 choice('grit','Một việc có thể làm xong. Rồi nghỉ.','One thing I can finish. Then rest.','Bạn xắn tay áo, rồi hạ tay áo xuống. Cả hai động tác đều có ích.','You roll up your sleeves. Then roll them down. Both gestures have their uses.','Quyền được dừng','Permission to stop'),
 choice('chaos','Một chuyện hay để kể. Tương lai tự mang ghế.','A good story. The future can bring its own chair.','Cánh cửa mở ra tiếng cười. Nó không trả lương, nhưng hôm nay bạn đâu đi phỏng vấn.','The door opens onto laughter. It does not pay a salary. But today was never a job interview.','Chuyện để kể sau','A story for later') ] }
];
export interface Ending { id:string; icon:string; title:Line; text:Line; reflection:Line }
export const ENDINGS:Ending[] = [
 {id:'clarity',icon:'compass',title:line('Người vẽ đường bằng bút chì','The Pencil Cartographer'),text:line('Bạn không tìm thấy câu trả lời cuối cùng. Bạn tìm thấy một câu hỏi tốt hơn, và chừa chỗ tẩy xóa. Thành phố đánh giá cao điều đó. Nó cũng đang sửa bản đồ.','You found no final answer. You found a better question, with room for erasing. The city approves. It is revising its map too.'),reflection:line('Thử chọn một bước nhỏ, có ngày hẹn. Đừng bắt nó phải chứng minh cả cuộc đời.','Try one small step with a date. Do not make it justify your entire life.')},
 {id:'care',icon:'heart-pulse',title:line('Người giữ một ngọn đèn','Keeper of the Porch Light'),text:line('Bạn không cứu thành phố. Bạn khiến vài căn phòng bớt lạnh. Có những thay đổi không đủ lớn để làm báo cáo, nhưng đủ lớn để một người ở lại.','You did not save the city. You made a few rooms less cold. Some changes are too small for a report and large enough to make someone stay.'),reflection:line('Giữ chỗ cho người khác. Nhớ ghi tên mình vào danh sách đó.','Make room for people. Remember to include your own name on that list.')},
 {id:'grit',icon:'wrench-adjustable',title:line('Thợ sửa những thứ còn dùng được','Repairer of Mostly Working Things'),text:line('Bạn ra về với tay dính dầu và một con dấu. Thế giới chưa vận hành trơn tru. Nhưng một chiếc đèn đã sáng, một cái cốc đã sạch. Hôm nay có bằng chứng.','You leave with oily hands and a stamp. The world still runs badly. But a light is on and a cup is clean. Today has evidence.'),reflection:line('Hoàn thành một việc vừa sức. Nghỉ cũng là bảo trì, không phải hỏng hóc.','Finish something manageable. Rest is maintenance, not a malfunction.')},
 {id:'chaos',icon:'lightning-charge',title:line('Ủy viên phụ trách chuyện vô lý','Commissioner for Unnecessary Wonders'),text:line('Bạn đã làm lệch vài thủ tục, mua cà phê bằng một câu đùa, và nâng bồ câu lên thành học thuyết. Không nên lập chính sách dựa trên hôm nay. Nên kể lại nó.','You bent several procedures, bought coffee with a joke, and promoted a pigeon into a doctrine. Today should not inform public policy. It should be retold.'),reflection:line('Cho ý tưởng lạ một sân chơi nhỏ. Nó không cần chiếm cả cuộc đời mới đáng vui.','Give the odd idea a small playground. It need not take over your life to be worth enjoying.')},
 {id:'ensemble',icon:'people',title:line('Ban nhạc chưa tập nhưng vẫn chơi','The Unrehearsed Orchestra'),text:line('Không giọng nào thắng tuyệt đối. La bàn, ngọn đèn, cờ lê và ý tưởng tệ cùng lên xe. Ồn ào, nhưng ít nhất không ai bị bỏ ở trạm.','No voice wins outright. Compass, light, wrench and terrible idea all board the bus. Noisy, yes. At least nobody is left at the stop.'),reflection:line('Bạn được phép có nhiều cách phản ứng. Không phải mọi ngày đều cần cùng một phiên bản của bạn.','You may have more than one way to respond. Not every day requires the same version of you.')},
 {id:'pigeon',icon:'stars',title:line('Bồ câu tạm quyền ngày mai','Acting Pigeon of Tomorrow'),text:line('Giấy phép vô nghĩa, đồ uống đã-cố và học thuyết bồ câu: ba vật đủ mở một cửa bí mật. Bạn bước ra, không tối ưu hơn. Chỉ nhẹ hơn. Sở coi đây là lỗi. Bạn coi là nghỉ trưa.','A permit for pointlessness, a serving of trying, and pigeon doctrine: three things open a secret door. You emerge no more optimised. Just lighter. The Department calls it a bug. You call it lunch.'),reflection:line('Không cần rút bài học từ mọi niềm vui. Có lúc, vui là đủ.','You do not have to extract a lesson from every pleasure. Sometimes enjoying it is enough.')}
];
export function resolveEnding(route:readonly number[]):Ending {
 if(route.length!==SCENES.length || route.some((n,i)=>!Number.isInteger(n)||!SCENES[i].choices[n])) throw new Error('Invalid story route');
 if(route[2]===3&&route[3]===3&&route[4]===3) return ENDINGS[5];
 const counts=VOICES.map(v=>route.filter((n,i)=>SCENES[i].choices[n].voice===v.id).length);
 const max=Math.max(...counts);
 return max>=4 ? ENDINGS[counts.indexOf(max)] : ENDINGS[4];
}
export function validRoute(value:unknown):value is number[] {
 return Array.isArray(value)&&value.length<=SCENES.length&&value.every((n,i)=>Number.isInteger(n)&&!!SCENES[i].choices[n]);
}
